### ISSUE TITLE
Decrapation of time.clock() method in python 3.8

### ISSUE THREAD

**Issue by raserhin** [iKevinY/EulerPy#28]
As you can see in [this issue](https://github.com/python/cpython/pull/13270) from the [CPython](https://github.com/python/cpython) repository the method time.clock() has been removed as of version 3.8 ([Official python bug](https://bugs.python.org/issue36895)). 

In your `clock()` function inside the `utils` module you are using this method making this whole package unusable (in case the `resource` module is not importable) 
```
# Use the resource module instead of time.clock() if possible (on Unix)
try:
    import resource

except ImportError:
    import time

    def clock():
        """
        Under Windows, system CPU time can't be measured. Return time.clock()
        as user time and None as system time.
        """
        return time.clock(), None

else:
    def clock():
        """
        Returns a tuple (t_user, t_system) since the start of the process.
        This is done via a call to resource.getrusage, so it avoids the
        wraparound problems in time.clock().
        """
        return resource.getrusage(resource.RUSAGE_CHILDREN)[:2]
```

I don't know how willingly are you about still maintaining this repository.  But I had to change this locally in my windows machine.

**Comment by iKevinY** [comment]
Thank you for the heads up! It's definitely been several years since I've touched this project, but the patch was simple enough, so I've gone and addressed this (hopefully) in 076dc90d0ad073b584f87114cac930a6c11d2129, and added Python 3.8 to the build matrix to catch other regressions.

I'll try to push a new package release if I can remember how to do that…
